spring:
  profiles:
    active:
      - local
    group:
      "local": "testdb,common"
      "dev":  "testdb,common"
      "prod": "proddb,common"
---
spring:
  config:
    activate:
      on-profile: "proddb"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME}?characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


---
spring:
  config:
    activate:
      on-profile: "testdb"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/final_project?characterEncoding=UTF-8
    username: bigdata
    password: bigdata
  
 
---

spring:
  config:
    activate:
      on-profile: "common"
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    view:
      prefix: /WEB-INF
      suffix: .jsp

server:
  port: 8080
  tomcat:
    use-relative-redirects: true  
  servlet:
    context-path: /gongo

    




