
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /gongo/
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/app-root: /gongo
      nginx.ingress.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:421576594835:certificate/239e7d02-3d7e-43c8-9051-5404b2c8ac20


spec:
  ingressClassName: nginx
#   tls:
#   - hosts:
#       - test.gazami.click
#     secretName: nginx  
  rules:
  - host: test.gazami.click
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: spring-service
            port:
              number: 8080        

