---
kind: Service
apiVersion: v1
metadata:
 name: mysql-rds
Spec:
 type: ClusterIP
 ports:
 - port: 3306
   targetPort: 3306
   
---

kind: Endpoints
apiVersion: v1
metadata:
 name: mysql-rds
subsets:
 - addresses:
     - ip: 10.0.32.192
