apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example
  namespace: gongo
spec:
  selector:
    matchLabels:
      app: spring
  endpoints:
  - port: http-spring
    path: /gongo
  namespaceSelector:
    any: true
