apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      imagePullSecrets:
      - name: regcred
      
      containers:
      - name: config-demo
        image: ghcr.io/gazami99/spring:latest
        
        env:      
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: gongo-secret
              key: dbHostName
              
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: gongo-secret
              key: databaseName
              
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: gongo-secret
              key: dbUserName
              
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gongo-secret
              key: dbPassword
        ports:
        - containerPort: 8080
              

      
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: gongo
spec:
  ports:
  - port: 8080
    name: spring-http
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring

