apiVersion: v1
kind: Service
metadata:
  name: spring-service

spec:
  selector:
    app: spring
  type: ExternalName
  sessionAffinity: None
  externalName: database-1.cpjbyuaaolfs.ap-northeast-2.rds.amazonaws.com
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
