apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: gongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: ghcr.io/gazami99/spring:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      - env:      
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: gongo-secret
              key: dbUserName

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gongo-secret
              key: dbPassword

         - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: gongo-secret
              key: databaseName

        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: gongo-secret
              key: dbHostName
      
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: gongo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring
