apiVersion: v1
kind: Service
metadata:
  name: spring   
spec:
  type: NodePort
  ports:
  - name: service
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32000
  selector:
    app: spring
  
