apiVersion: v1
kind: Service
metadata:
  name: spring   
spec:
  type: NodePort     # 서비스 타입
  ports:
  - port: 8080       # 서비스 포트
    targetPort: 8080   # 타켓, 즉 pod의 포트
    protocol: TCP
    name: our
  selector:
    app: spring
