apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  containers:
  - image: 421576594835.dkr.ecr.ap-northeast-2.amazonaws.com/docker-spring:spring_image
  imagePullSecrets:
  - name: ap-northeast-2-ecr-registry
