name: Deploy to Amazon ECR Spring

on:
  push:
    paths:
      - 'FPBoot-deploy/**'

  pull_request:
      paths:
      - 'FPBoot-deploy/**'
 

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: 'final_project'
          MYSQL_USER: 'bigdata'
          MYSQL_PASSWORD: 'bigdata'
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" 
                 --health-interval=10s 
                 --health-timeout=5s 
                 --health-retries=3

   
    steps:

    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --f ./FPBoot-deploy/pom.xml
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.TOKEN_CONTAINER }}

    - name: Build, tag, and push image to Github CR
      run: |
        docker buildx build --file ./docker/spring/Dockerfile --platform linux/arm64 -t ghcr.io/${{ github.repository_owner }}/spring:latest --push --no-cache .
